### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by jedymatt** [jedymatt/sari_sari_store_price_scanner#1]
# To-Do Features

- [x] #2
- [x] Display list of products. 
- [ ] Register product along with price option when a barcode does not exist in local storage.
- [ ] Manage the products and prices screen.
- [ ] Export and import file for backup and restore data.
- [ ] (Optional and is only for convenience) Standalone static website for managing the products and prices, without backend. Utilizes import and export file. The exported file will be used to import in android application. 
- [ ] Add "Utang" list
